services:
  backend:
    build: .
    ports:
      - "2000:2000"
    depends_on:
      db:
        condition: "service_healthy"
    restart: always
  db:
    image: "postgres:17-alpine"
    restart: "always"
    environment:
      POSTGRES_PASSWORD: "/run/secrets/db_password"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - db_password
volumes:
  db-data:
    external: true
secrets:
  db_password:
    file: db_password.txt
